export const PRIMARY = '#5838D5'
export const DARKER = '#464676'
export const BLACK = '#3C3C3C'
export const GRAY = '#ADADAD'
export const LIGHT_GRAY = '#F1F3F4'
export const GREEN = '#8AD492'
export const RED = '#E85C5C'
export const LIGHT_PURPLE = '#ECE7FF'